const Data = [
    {
      id: 1,
      category: "education",
      icon: "icon-graduation",
      year: "2019 - 2025",
      title: "Bachelor of Computer Science",
      place: "University of Waterloo",
      desc: "- GPA: 3.5/4.0",
    },
    {
      id: 2,
      category: "education",
      icon: "icon-graduation",
      year: "2019 - 2025",
      title: "Bachelor of Business Administration",
      place: "Wilfrid Laurier University",
      desc: "- Finance Concentration \n- GPA: 3.5/4.0",
    },
    {
      id: 3,
      category: "education",
      icon: "icon-graduation",
      year: "2015 - 2019",
      title: "High School Diploma",
      place: "Corpus Christi Catholic Secondary School",
      desc: "- Senior Year Grade: 95%",
    },
    {
      id: 4,
      category: "experience",
      icon: "icon-briefcase",
      year: "Sep 2023 - Aug 2024",
      title: "Data Engineer Intern",
      place: "Royal Bank of Canada",
      // desc: "- Python, SQL, Dataiku, ETLs, Automation",
    },
    {
      id: 5,
      category: "experience",
      icon: "icon-briefcase",
      year: "Sep 2022 - Dec 2022",
      title: "Data Automation Developer Intern",
      place: "Motoinsight",
      // desc: "DevOps, ETLs, Data Visualization",
    },
    {
      id: 6,
      category: "experience",
      icon: "icon-briefcase",
      year: "Jan 2022 - Apr 2022",
      title: "Analyst Intern",
      place: "Blackhawk Network Canada",
      // desc: "Chief Audit Executive (Internal Audit) Group",
    },
    {
      id: 7,
      category: "experience",
      icon: "icon-briefcase",
      year: "Jan 2021 - Apr 2021",
      title: "Staff Accountant",
      place: "KRP LLP",
      // desc: "Chief Audit Executive (Internal Audit) Group",
    },
  ];

export default Data